### ISSUE TITLE
When I run my App I had this error  image_gallery_saver:compileDebugKotlin

### ISSUE THREAD

**Issue by winsweba** [hui-z/image_gallery_saver#101]
FAILURE: Build failed with an exception.

    What went wrong:
    Execution failed for task ':image_gallery_saver:compileDebugKotlin'.

    Could not resolve all artifacts for configuration ':image_gallery_saver:debugCompileClasspath'.
    Failed to transform artifact 'kotlin-stdlib.jar (org.jetbrains.kotlin:kotlin-stdlib:1.3.72)' to match attributes {artifactType=android-classes, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
    > Execution failed for JetifyTransform: C:\Users\Winchester.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.3.72\8032138f12c0180bc4e51fe139d4c52b46db6109\kotlin-stdlib-1.3.72.jar.
    > Cannot parse result path string:

**Comment by hyjfine** [comment]
please show you flutter doctor, gradle & kotlin plugin version

**Comment by winsweba** [comment]
![Imp](https://user-images.githubusercontent.com/40374625/88987184-020dcc80-d28a-11ea-9cb4-9e63e4910e93.PNG)

**Comment by rohithaider** [comment]
The plugin `admob_flutter` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
Launching lib\main.dart on Redmi Note 8 Pro in debug mode...
Running Gradle task 'assembleDebug'...
Invalid depfile: D:\java_files\freelance\mqs-flutter-app\hindiShayariwold\.dart_tool\flutter_build\612247b5f7241794190553b52ff381f1\kernel_snapshot.d
Invalid depfile: D:\java_files\freelance\mqs-flutter-app\hindiShayariwold\.dart_tool\flutter_build\612247b5f7241794190553b52ff381f1\kernel_snapshot.d
e: D:\android\flutter_sdk\flutter_windows_2.5.3-stable\flutter\.pub-cache\hosted\pub.dartlang.org\image_gallery_saver-1.6.9\android\src\main\kotlin\com\example\imagegallerysaver\ImageGallerySaverPlugin.kt: (19, 7): Redeclaration: ImageGallerySaverPlugin
e: D:\android\flutter_sdk\flutter_windows_2.5.3-stable\flutter\.pub-cache\hosted\pub.dartlang.org\image_gallery_saver-1.6.9\android\src\main\kotlin\com\example\imagegallerysaver\ImageGallerySaverPlugin.kt: (113, 7): Redeclaration: SaveResultModel
e: D:\android\flutter_sdk\flutter_windows_2.5.3-stable\flutter\.pub-cache\hosted\pub.dartlang.org\image_gallery_saver-1.7.1\android\src\main\kotlin\com\example\imagegallerysaver\ImageGallerySaverPlugin.kt: (26, 7): Redeclaration: ImageGallerySaverPlugin
e: D:\android\flutter_sdk\flutter_windows_2.5.3-stable\flutter\.pub-cache\hosted\pub.dartlang.org\image_gallery_saver-1.7.1\android\src\main\kotlin\com\example\imagegallerysaver\ImageGallerySaverPlugin.kt: (34, 52): No value passed for parameter 'registrar'
e: D:\android\flutter_sdk\flutter_windows_2.5.3-stable\flutter\.pub-cache\hosted\pub.dartlang.org\image_gallery_saver-1.7.1\android\src\main\kotlin\com\example\imagegallerysaver\ImageGallerySaverPlugin.kt: (35, 22): Unresolved reference: onAttachedToEngine
e: D:\android\flutter_sdk\flutter_windows_2.5.3-stable\flutter\.pub-cache\hosted\pub.dartlang.org\image_gallery_saver-1.7.1\android\src\main\kotlin\com\example\imagegallerysaver\ImageGallerySaverPlugin.kt: (159, 7): Redeclaration: SaveResultModel

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':image_gallery_saver:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 19s
Exception: Gradle task assembleDebug failed with exit code 1
