### ISSUE TITLE
Flutter gives an error on running a project with the package

### ISSUE THREAD

**Issue by kmilo2622** [hui-z/image_gallery_saver#181]
Hello,

Today I run the commando "flutter upgrade" and after the upgrading when I try to run my app I get this error:

The plugin `image_gallery_saver` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2
embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding:
https://flutter.dev/go/android-plugin-migration.

What should I do?

**Comment by kmilo2622** [comment]
> > Hello,
> > Today I run the commando "flutter upgrade" and after the upgrading when I try to run my app I get this error:
> > The plugin `image_gallery_saver` uses a deprecated version of the Android embedding.
> > To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2
> > embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
> > If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding:
> > https://flutter.dev/go/android-plugin-migration.
> > What should I do?
> 
> 1.Use latest version
> 2.compileSdkVersion 30
> 3.targetSdkVersion 30

This also didn't work for me, getting the same message

**Comment by ZahraVe** [comment]
Has anyone got any solution? same issue here!!!

The plugin `image_gallery_saver` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
Process finished with exit code 0

**Comment by woodwen** [comment]
fix
