### ISSUE TITLE
The plugin `image_gallery_saver` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by Pavel401** [hui-z/image_gallery_saver#188]
The plugin `image_gallery_saver` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration

**Comment by hu70258tao** [comment]
> The plugin `image_gallery_saver` uses a deprecated version of the Android embedding.
> To avoid unexpected runtime failures or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
> If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration

look #186

**Comment by bueltan** [comment]
Changed 1 dependency!
The plugin `image_gallery_saver` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise,
consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding:
https://flutter.dev/go/android-plugin-migration.

**Comment by JonYun** [comment]
Has your problem been solved?
