### ISSUE TITLE
保存图片时UI线程卡顿，创建compute报错 - UI thread gets stuck when saving pictures, getting error when create by compute

### ISSUE THREAD

**Issue by xiexinhua2006** [hui-z/image_gallery_saver#222]
保存的时候会导致UI线程卡顿，卡顿时间根据图片大小而定
在尝试使用compute创建新线程保存时会报错，不知道该如何解决，希望得到解答

Saving will cause the UI thread to get stuck. The stuck time depends on the size of the image
An error will be reported when trying to create a new thread by using compute to save. I don't know how to solve it, but I hope it can be solved

Thanks.

**Comment by xiexinhua2006** [comment]
compute时的报错 platform_channal.dart
BinaryMessenger get binaryMessenger => _binaryMessenger ?? ServicesBinding.instance!.defaultBinaryMessenger;

exception = {_CastError} Null check operator used on a null value

**Comment by SomaNonaka** [comment]
I think this is because `ImageGallarySaver` calls a native method with `invokeMethod` (https://github.com/hui-z/image_gallery_saver/blob/master/lib/image_gallery_saver.dart#L19), which is currently only supported in the main thread. But the flutter team are now trying to make it possible for `invokeMethod` to run a different thread (https://github.com/flutter/flutter/issues/13937). I think this issue will be resolved once these changes are merged.
